/**
 * generated by Xtext 2.12.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.RipDSLRuntimeModule;
import org.xtext.RipDSLStandaloneSetup;
import org.xtext.ide.RipDSLIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RipDSLIdeSetup extends RipDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    RipDSLRuntimeModule _ripDSLRuntimeModule = new RipDSLRuntimeModule();
    RipDSLIdeModule _ripDSLIdeModule = new RipDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_ripDSLRuntimeModule, _ripDSLIdeModule));
  }
}
