/**
 * generated by Xtext 2.12.0
 */
package org.xtext;

import org.xtext.RipDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RipDSLStandaloneSetup extends RipDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new RipDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
