/**
 * generated by Xtext 2.12.0
 */
package org.xtext;

import org.xtext.AbstractRipDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RipDSLRuntimeModule extends AbstractRipDSLRuntimeModule {
}
