/*
 * generated by Xtext 2.12.0
 */
package org.xtext.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.RipDSLRuntimeModule
import org.xtext.RipDSLStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class RipDSLIdeSetup extends RipDSLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new RipDSLRuntimeModule, new RipDSLIdeModule))
	}
	
}
